<?php
/**
 * Created by PhpStorm.
 * User: xmy 280564871@qq.com
 * Date: 2017/4/6
 * Time: 16:36
 */

namespace Admin\Controller;

use Admin\Model\PointShopRecordModel;

class PointShopRecordController extends ThinkController{


	public function _initialize()
	{
		$this->meta_title = "购买记录";
		return parent::_initialize(); // TODO: Change the autogenerated stub
	}

	public function lists($p=1)
	{
		$model = new PointShopRecordModel();
		I('good_id') == "" || $map['sr.good_id'] = I('good_id');
		I('status') == "" || $map['sr.status'] = I('status');
		empty(I("account")) || $map['u.account'] = ["like","%".I("account")."%"];
		empty(I("good_key")) || $map['sr.good_key'] = ["like","%".I("good_key")."%"];
		
		if (!empty($_REQUEST['time_start']) && !empty($_REQUEST['time_end'])) {
			$map['sr.create_time'] = array('BETWEEN',array(strtotime($_REQUEST['time_start']),strtotime($_REQUEST['time_end'])+24*60*60-1));
			
		} elseif (!empty($_REQUEST['time_start']) ) {
			$map['sr.create_time'] = array('BETWEEN',array(strtotime($_REQUEST['time_start']),time()));
			
		} elseif (!empty($_REQUEST['time_end']) ) {
			$map['sr.create_time'] = array('elt',strtotime($_REQUEST['time_end'])+24*60*60-1);
			
		}

        $row = intval(C('LIST_ROWS')) ? :10;
		$data = $model->getLists($map,"create_time desc",$p,$row);
		$this->assign("data",$data['data']);

		//分页
		$count = $data['count'];

		if($count > $row){
			$page = new \Think\Page($count, $row);
			$page->setConfig('theme','%UP_PAGE% %FIRST% %LINK_PAGE% %END% %DOWN_PAGE% %HEADER%');
			$this->assign('_page', $page->show());
		}

		$this->display();
	}
	
	public function shipment($model="PointShopRecord"){
	    if(isset($_REQUEST['model'])){
	        $model=$_REQUEST['model'];
	        unset($_REQUEST['model']);
	    }
	    parent::set_status($model);
	}
}