<?php
/**
 * Created by PhpStorm.
 * User: xmy 280564871@qq.com
 * Date: 2017/4/1
 * Time: 10:22
 */

namespace Admin\Controller;


use Admin\Model\PointRecordModel;

class PointRecordController extends ThinkController{

	public function _initialize()
	{
		$this->meta_title = "积分获取记录";
		return parent::_initialize(); // TODO: Change the autogenerated stub
	}

	public function lists($p=1){
		$model = new PointRecordModel();
		empty(I('type_id')) || $map['pr.type_id'] = I('type_id');
		empty(I("account")) || $map['u.account'] = ["like","%".I("account")."%"];
		
		if (!empty($_REQUEST['time_start']) && !empty($_REQUEST['time_end'])) {
			$map['pr.create_time'] = array('BETWEEN',array(strtotime($_REQUEST['time_start']),strtotime($_REQUEST['time_end'])+24*60*60-1));
			
		} elseif (!empty($_REQUEST['time_start']) ) {
			$map['pr.create_time'] = array('BETWEEN',array(strtotime($_REQUEST['time_start']),time()));
			
		} elseif (!empty($_REQUEST['time_end']) ) {
			$map['pr.create_time'] = array('elt',strtotime($_REQUEST['time_end'])+24*60*60-1);
			
		}
        $row = C('LIST_ROWS') ? C('LIST_ROWS') : 10;
		$data = $model->getLists($map,'create_time desc',$p,$row);

		//分页
		$count = $data['count'];
		if($count > $row){
			$page = new \Think\Page($count, $row);
			$page->setConfig('theme','%UP_PAGE% %FIRST% %LINK_PAGE% %END% %DOWN_PAGE% %HEADER%');
			$this->assign('_page', $page->show());
		}

		$this->assign("data",$data['data']);
		$this->display();
	}

}