<?php
/**
 * Created by PhpStorm.
 * User: xmy 280564871@qq.com
 * Date: 2017/5/5
 * Time: 16:22
 */

namespace Common\Model;


use Think\Model;

class BaseModel extends Model {

	public function _initialize()
	{
		$this->tablePrefix = "tab_";
		parent::_initialize(); // TODO: Change the autogenerated stub
	}
}